// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwBjdUm0YLWZ8QpaWfy6rRi5Xe4w5x8WM',
    appId: '1:75142720474:web:a7ae58cb2c2994e16d6ee3',
    messagingSenderId: '75142720474',
    projectId: 'car-wash-3252a',
    authDomain: 'car-wash-3252a.firebaseapp.com',
    storageBucket: 'car-wash-3252a.appspot.com',
    measurementId: 'G-6W97RJH979',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATyjJLAfqBdqE6xbe1NxQlr_7WJdUyjIk',
    appId: '1:75142720474:android:9164b1922348c0f76d6ee3',
    messagingSenderId: '75142720474',
    projectId: 'car-wash-3252a',
    storageBucket: 'car-wash-3252a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZRsYOdXNuaoT-xJnns761Jl7YuE2fkkM',
    appId: '1:75142720474:ios:8705384bd90b6d836d6ee3',
    messagingSenderId: '75142720474',
    projectId: 'car-wash-3252a',
    storageBucket: 'car-wash-3252a.appspot.com',
    iosBundleId: 'com.example.carwashing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZRsYOdXNuaoT-xJnns761Jl7YuE2fkkM',
    appId: '1:75142720474:ios:8705384bd90b6d836d6ee3',
    messagingSenderId: '75142720474',
    projectId: 'car-wash-3252a',
    storageBucket: 'car-wash-3252a.appspot.com',
    iosBundleId: 'com.example.carwashing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwBjdUm0YLWZ8QpaWfy6rRi5Xe4w5x8WM',
    appId: '1:75142720474:web:1c743a1a23ee01e96d6ee3',
    messagingSenderId: '75142720474',
    projectId: 'car-wash-3252a',
    authDomain: 'car-wash-3252a.firebaseapp.com',
    storageBucket: 'car-wash-3252a.appspot.com',
    measurementId: 'G-NHB71TL44Y',
  );
}
